### ISSUE TITLE
Can I have an example with create-react-app?

### ISSUE THREAD

**Issue by rainstormza** [ghengeveld/react-webworker#2]
Can I have an example with create-react-app?

I've tried to implement this lib within create-react-app project but it does not work.
It seems my worker.js has something wrong.

![image](https://user-images.githubusercontent.com/4003032/48335093-4fe63980-e68f-11e8-82c8-59102fc2d277.png)

component.js

```
 <WebWorker url="/worker.js">
    {({ data, error, postMessage }) => {
      if (error) return `Something went wrong: ${error.message}`
      if (data)
        return (
          <div>
            <strong>Received some data:</strong>
            <pre>{JSON.stringify(data, null, 2)}</pre>
          </div>
        )
      return <button onClick={() => postMessage('hello')}>Hello</button>
    }}
  </WebWorker>
```

https://codesandbox.io/s/ox85ooo31q

**Comment by rainstormza** [comment]
https://codesandbox.io/s/ox85ooo31q

https://spectrum.chat/thread/45727df4-6d3b-4392-a771-218c09329333

mention about the solution in those link.

**Comment by hkyq** [comment]
@rainstormza @ghengeveld The sandbox is 404'ing, can we get an updated example?

**Comment by ghengeveld** [comment]
Here's a basic sandbox with CRA: https://codesandbox.io/s/bold-blackwell-vxxth

**Comment by Lcj-space** [comment]
> Here's a basic sandbox with CRA: https://codesandbox.io/s/bold-blackwell-vxxth
The sandbox is 404'ing

**Comment by ghengeveld** [comment]
Here's another: https://codesandbox.io/s/react-webworker-cra-example-3fjim

**Comment by ghengeveld** [comment]
The gist is to put the worker file in `/public`.
